sonar.projectKey=pepinshriya_cartiva-pepin
sonar.organization=pepinshriya
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.zip
