name: CI - Frontend

on:
  push:
    branches: [develop, main]
    paths:
      - 'frontend/**'
      - '.github/workflows/reusable-backend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  backend-ci:
    name: Frontend CI
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service: frontend
