name: CI - Order Service

on:
  push:
    branches: [develop, main]
    paths:
      - 'order-service/**'
      - '.github/workflows/reusable-backend-ci.yml'
  pull_request:
    paths:
      - 'order-service/**'
  workflow_dispatch:

jobs:
  backend-ci:
    name: Backend CI
    uses: ./.github/workflows/reusable-backend-ci.yml
    with:
      service: order-service
